[package]
name = "lambda_test"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda_runtime = "0.5.0"
serde_json = "1.0.79"
tokio = "1.17.0"
tracing = "0.1.31"
tracing-subscriber = {version = "0.3.9", features = ["env-filter"]}
